name: Test Push Authentication

on:
  workflow_dispatch:
  push:
    branches:
      - test-push-workflow

jobs:
  test-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Test Push Methods
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "=== Testing Push Authentication ==="
          
          # Test 1: Direct HTTPS with token
          echo -e "\n1. Testing direct HTTPS push..."
          git config user.email "robottonik@users.noreply.github.com"
          git config user.name "robottonik"
          
          TEST_BRANCH="test-$(date +%s)"
          git checkout -b "$TEST_BRANCH"
          echo "Test at $(date)" > test-file.txt
          git add test-file.txt
          git commit -m "Test commit"
          
          # Method 1: Set remote URL
          echo -e "\nMethod 1: git remote set-url"
          git remote set-url origin https://robottonik:${BOT_TOKEN}@github.com/${{ github.repository }}.git
          git remote -v
          
          if git push origin "$TEST_BRANCH"; then
            echo "✅ Method 1 worked!"
            git push origin --delete "$TEST_BRANCH"
          else
            echo "❌ Method 1 failed"
          fi
          
          # Reset
          git checkout master
          git branch -D "$TEST_BRANCH"
          
          # Method 2: Using gh CLI
          echo -e "\nMethod 2: GitHub CLI"
          if command -v gh &> /dev/null; then
            gh auth status || echo "$BOT_TOKEN" | gh auth login --with-token
            gh auth status
            
            git checkout -b "${TEST_BRANCH}-gh"
            echo "Test GH at $(date)" > test-gh.txt
            git add test-gh.txt
            git commit -m "Test GH commit"
            
            if git push origin "${TEST_BRANCH}-gh"; then
              echo "✅ Method 2 worked!"
              gh api repos/${{ github.repository }}/git/refs/heads/${TEST_BRANCH}-gh -X DELETE
            else
              echo "❌ Method 2 failed"
            fi
          else
            echo "gh CLI not available"
          fi
          
          # Method 3: Using GITHUB_TOKEN from checkout
          echo -e "\nMethod 3: Default GITHUB_TOKEN"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git checkout -b "${TEST_BRANCH}-default"
          echo "Test default at $(date)" > test-default.txt
          git add test-default.txt
          git commit -m "Test default commit"
          
          if git push origin "${TEST_BRANCH}-default"; then
            echo "✅ Method 3 worked!"
          else
            echo "❌ Method 3 failed (expected)"
          fi
          
          echo -e "\n=== Test Complete ==="